#!/bin/sh

set -e

#DEBHELPER#

case "$1" in
  configure)
    if test -n "$2"; then
      # TODO: remove once PVE 10.0 is released
      if dpkg --compare-versions "$2" 'lt' '2.0.1'; then
        ln -s -f /run/pve-lxc-syscalld/socket /run/pve/lxc-syscalld.sock
      fi
    fi
    ;;

esac

exit 0
